name: Java CI

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: what broswer used for test?
        required: true
        default: chrome
        options:
          - Chrome
          - Firefox
      url:
        required: true
        description: which url used for test?
        default: 'https://magento.softwaretestingboard.com/'

  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn clean install

      - name: Run tests
        run: mvn test -Dbrowser=${{ inputs.browser }} -Durl=${{ inputs.url }}
        continue-on-error: false



        